export const BET_TYPES = {
  HIGHER: 'HIGHER',
  LOWER: 'LOWER'
};

export const HAND_RESULTS = {
  WIN: 'WIN',
  LOSS: 'LOSS',
  PUSH: 'PUSH'
};

export const GAME_ACTIONS = {
  START_GAME: 'START_GAME'
};

export const GAME_OVER_REASONS = {
  BOUNDARY_HIT: 'BOUNDARY_HIT',
  DECK_EXHAUSTED: 'DECK_EXHAUSTED',
  CHEAT_DETECTED: 'CHEAT_DETECTED'
};