export const GAME_CONFIG = {
  HAND_SIZE: 5,
  INITIAL_SCORE: 0,
  MAX_RESHUFFLES: 3,
  DYNAMIC_MIN: 0,
  DYNAMIC_MAX: 10,
  WIN_SCORE_BASE: 10,
  LOSS_PENALTY: -15,
  SOUND_DISABLED: import.meta.env.VITE_SOUND_DISABLED === 'true'
};