export const GAME_CONFIG = {
  HAND_SIZE: 5,
  INITIAL_SCORE: 0,
  MAX_RESHUFFLES: 3,
  DYNAMIC_MIN: 0,
  DYNAMIC_MAX: 10,
  WIN_SCORE_BASE: 10,
  LOSS_PENALTY: -15,
  BET_ANIMATION_TIMELINE_MS: {
    FEEDBACK: 700,
    EXIT: 320,
    DISTRIBUTION: 650
  },
  DEFAULT_FEEDBACK_POSITION: {
    x: 0,
    y: 0
  },
  RANK_THRESHOLDS: {
    LEGEND: 500,
    EXPERT: 200
  },
  LEADERBOARD_FETCH_INTERVAL: Number(import.meta.env.VITE_LEADERBOARD_INTERVAL) || 5000,
  STORAGE_KEYS: {
    PLAYER_NAME: 'mahjong_player_name',
    HISTORY: 'mahjong_betting_history'
  },
  RESHUFFLE_DELAY_MS: 800,
  MAX_HISTORY_ITEMS: 50,
  SOUND_DISABLED: import.meta.env.VITE_SOUND_DISABLED === 'true'
};