export const UI_CONFIG = {
  PLAYER_NAME_MIN_LEN: 3,
  PLAYER_NAME_MAX_LEN: 16,
  DRAW_LANE_PREVIEW_MAX: 5,
  DRAW_LANE_MIN_HEIGHT_CLASS: 'min-h-[180px]',
  GAME_HISTORY_PANEL_HEIGHT_CLASS: 'h-[640px]',
  GAME_HISTORY_PANEL_MAX_HEIGHT_CLASS: 'max-h-[calc(100vh-8rem)]'
};