#!/bin/bash

# --- CONFIGURATION ---
ENV_FILE=".env"
FRONTEND_DIR="apps/frontend"
BACKEND_DIR="apps/backend"

# Dynamically extract paths from Backend source code
get_backend_const() {
    local file=$1
    local key=$2
    local fallback=$3
    if [ -f "$BACKEND_DIR/internal/constants/$file" ]; then
        local val=$(grep "$key" "$BACKEND_DIR/internal/constants/$file" | cut -d'"' -f2)
        echo "${val:-$fallback}"
    else
        echo "$fallback"
    fi
}

API_BASE=$(get_backend_const "routes.go" "APIBasePath" "/api")
HEALTH_PATH=$(get_backend_const "app.go" "HealthPath" "/api/health")
ADMIN_PATH=$(get_backend_const "routes.go" "AdminPath" "/admin")
RESET_PATH=$(get_backend_const "routes.go" "ResetPath" "/reset")

FULL_RESET_URL="${API_BASE}${ADMIN_PATH}${RESET_PATH}"
FULL_HEALTH_URL="${HEALTH_PATH}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# --- UTILS ---
log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

check_env() {
    if [ ! -f "$ENV_FILE" ]; then
        log_warn ".env file is missing!"
        echo -e "1) Create from .env.example (Fast)"
        echo -e "2) Step-by-Step Setup (Interactive)"
        echo -e "0) Cancel"
        read -p "Select an option [0-2]: " env_choice
        
        case $env_choice in
            1)
                if [ -f ".env.example" ]; then
                    cp .env.example "$ENV_FILE"
                    log_success ".env created from example."
                else
                    log_error ".env.example missing. Cannot proceed."
                    exit 1
                fi
                ;;
            2)
                env_wizard
                ;;
            *)
                log_error "Setup cancelled. Some commands may fail."
                return 1
                ;;
        esac
    fi
    # Load env variables
    export $(grep -v '^#' "$ENV_FILE" | xargs)
}

env_wizard() {
    log_info "Starting Step-by-Step Environment Setup..."
    if [ ! -f ".env.example" ]; then
        log_error ".env.example not found. Cannot start wizard."
        return 1
    fi

    # Clear or create .env
    echo "# --- GENERATED BY RUN.SH WIZARD ---" > "$ENV_FILE"
    
    while IFS= read -r line || [ -n "$line" ]; do
        # Handle Comments (Sections)
        if [[ $line =~ ^# ]]; then
            echo -e "\n${CYAN}--- ${line:2} ---${NC}"
            echo "$line" >> "$ENV_FILE"
            continue
        fi

        # Handle Empty Lines
        if [[ -z $line ]]; then
            echo "" >> "$ENV_FILE"
            continue
        fi

        # Extract Key and Default Value
        if [[ $line == *"="* ]]; then
            key=$(echo "$line" | cut -d'=' -f1)
            default_val=$(echo "$line" | cut -d'=' -f2-)

            # IMPORTANT: Use < /dev/tty to read from user instead of the redirected file
            read -p "Enter value for $key [default: $default_val]: " user_val < /dev/tty
            final_val=${user_val:-$default_val}
            
            echo "$key=$final_val" >> "$ENV_FILE"
        else
            # Just copy the line if it doesn't fit the pattern
            echo "$line" >> "$ENV_FILE"
        fi
    done < ".env.example"

    log_success ".env file has been generated and saved."
}

show_help() {
    echo -e "${CYAN}Betting Game Management Script${NC}"
    echo -e "Usage: ./run.sh [command] [options]"
    echo -e "Note: Running without arguments enters the ${YELLOW}Interactive Shell${NC}."
    echo ""
    echo -e "${YELLOW}Commands:${NC}"
    echo -e "  ${GREEN}start${NC} [--frontend|--backend|--all]  Start services manually (development mode)"
    echo -e "  ${GREEN}build${NC} [--frontend|--backend|--all]  Build services manually"
    echo -e "  ${GREEN}docker${NC} [up|down|build|restart|logs] Manage services via Docker Compose"
    echo -e "  ${GREEN}db${NC} [reset|config]                   Manage database (reset or update admin credentials)"
    echo -e "  ${GREEN}logs${NC} [--frontend|--backend]           View logs of manual processes or Docker"
    echo -e "  ${GREEN}check${NC}                               Verify system dependencies"
    echo -e "  ${GREEN}help${NC}                                Show this help menu"
    echo ""
    echo -e "${YELLOW}Examples:${NC}"
    echo -e "  ./run.sh start --all"
    echo -e "  ./run.sh docker up"
    echo -e "  ./run.sh db reset"
}

check_docker() {
    if [ -f /.dockerenv ] || grep -q 'docker' /proc/self/cgroup 2>/dev/null; then
        echo -e "  [${CYAN}DOCKER${NC}] Running inside a container."
        return 0
    else
        echo -e "  [${BLUE}NATIVE${NC}] Running on host system."
        return 1
    fi
}

check_deps() {
    echo -e "${CYAN}--- Dependency Check ---${NC}"
    check_docker
    local missing=0
    
    check_tool() {
        if command -v $1 >/dev/null 2>&1; then
            echo -e "  [${GREEN}OK${NC}] $1 ($( $1 --version 2>&1 | head -n 1 ))"
        else
            echo -e "  [${RED}MISSING${NC}] $1"
            missing=1
        fi
    }

    check_tool "go"
    check_tool "node"
    check_tool "npm"
    check_tool "docker"
    check_tool "curl"

    if [ $missing -eq 0 ]; then
        log_success "All core dependencies found."
    else
        log_warn "Some dependencies are missing. Some features may not work."
    fi
}

check_running_services() {
    echo -e "\n${CYAN}--- Service Status ---${NC}"
    
    # 1. Check Docker Containers
    if command -v docker >/dev/null 2>&1; then
        local containers=$(docker ps --format "{{.Names}}: {{.Status}}" | grep "betting-game\|mongodb")
        if [ -n "$containers" ]; then
            echo -e "${YELLOW}Docker Containers:${NC}"
            echo "$containers" | sed 's/^/  /'
        else
            echo -e "  [${YELLOW}OFFLINE${NC}] No betting-game Docker containers running."
        fi
    fi

    # 2. Check API Health
    check_env
    local port=${BACKEND_PORT:-8080}
    echo -e "\n${YELLOW}API Health Check:${NC}"
    local health=$(curl -s -m 2 "http://localhost:$port${FULL_HEALTH_URL}")
    if echo "$health" | grep -q "ok"; then
        echo -e "  [${GREEN}ONLINE${NC}] Backend API is healthy at http://localhost:$port${FULL_HEALTH_URL}"
    else
        echo -e "  [${RED}OFFLINE${NC}] Backend API is not responding at http://localhost:$port${FULL_HEALTH_URL}"
    fi

    # 3. Check Frontend Port
    local f_port=${FRONTEND_PORT:-5173}
    echo -e "\n${YELLOW}Port Availability:${NC}"
    if lsof -Pi :$f_port -sTCP:LISTEN -t >/dev/null ; then
        echo -e "  [${GREEN}ACTIVE${NC}] Port $f_port (Frontend) is occupied."
    else
        echo -e "  [${YELLOW}IDLE${NC}] Port $f_port (Frontend) is free."
    fi

    if lsof -Pi :$port -sTCP:LISTEN -t >/dev/null ; then
        echo -e "  [${GREEN}ACTIVE${NC}] Port $port (Backend) is occupied."
    else
        echo -e "  [${YELLOW}IDLE${NC}] Port $port (Backend) is free."
    fi

    # MongoDB Port
    if lsof -Pi :27017 -sTCP:LISTEN -t >/dev/null ; then
        echo -e "  [${GREEN}ACTIVE${NC}] Port 27017 (MongoDB) is occupied."
    else
        echo -e "  [${YELLOW}IDLE${NC}] Port 27017 (MongoDB) is free."
    fi
}

run_full_check() {
    check_deps
    check_running_services
}

# --- ACTIONS ---

ensure_frontend_deps() {
    if [ ! -d "$FRONTEND_DIR/node_modules" ]; then
        log_warn "node_modules missing in $FRONTEND_DIR. Running npm install..."
        cd "$FRONTEND_DIR" || exit
        npm install
        cd - > /dev/null || exit
    fi
}

start_backend() {
    log_info "Starting Backend..."
    cd "$BACKEND_DIR" || exit
    go run cmd/server/main.go
}

start_frontend() {
    ensure_frontend_deps
    log_info "Starting Frontend..."
    cd "$FRONTEND_DIR" || exit
    npm run dev
}

build_backend() {
    log_info "Building Backend..."
    cd "$BACKEND_DIR" || exit
    mkdir -p ../../bin
    go build -o ../../bin/server ./cmd/server
    log_success "Backend built in bin/server"
}

build_frontend() {
    log_info "Building Frontend..."
    ensure_frontend_deps
    cd "$FRONTEND_DIR" || exit
    npm run build
    log_success "Frontend built in $FRONTEND_DIR/dist"
}

docker_cmd() {
    local cmd=$1
    case $cmd in
        up)
            log_info "Starting Docker stack..."
            docker-compose up -d
            if [ $? -eq 0 ]; then
                log_success "Docker stack is UP!"
                echo -e "${CYAN}------------------------------------------${NC}"
                echo -e "  ${YELLOW}Frontend:${NC} http://localhost:${FRONTEND_PORT:-5173}"
                echo -e "  ${YELLOW}Backend:${NC}  http://localhost:${BACKEND_PORT:-8080}"
                echo -e "  ${YELLOW}MongoDB:${NC}  mongodb://localhost:27017"
                echo -e "${CYAN}------------------------------------------${NC}"
            fi
            ;;
        down)
            log_info "Stopping Docker stack..."
            docker-compose down
            ;;
        build)
            log_info "Building Docker images..."
            docker-compose build
            ;;
        restart)
            log_info "Restarting Docker stack..."
            docker-compose restart
            ;;
        logs)
            log_info "Tailing Docker logs..."
            docker-compose logs -f
            ;;
        *)
            log_error "Invalid docker command: $cmd"
            echo "Usage: ./run.sh docker [up|down|build|restart|logs]"
            ;;
    esac
}

db_reset() {
    check_env
    local port=${BACKEND_PORT:-8080}
    
    log_warn "SECURITY ALERT: You are about to RESET the entire database."
    read -p "Enter Admin Username: " input_user
    read -s -p "Enter Admin Token: " input_token
    echo "" # New line after secret input
    
    if [ -z "$input_user" ] || [ -z "$input_token" ]; then
        log_error "Credentials cannot be empty. Reset aborted."
        return 1
    fi

    log_info "Attempting to reset database via API..."
    log_info "Target: http://localhost:$port${FULL_RESET_URL}"
    
    local response=$(curl -s -X POST "http://localhost:$port${FULL_RESET_URL}" \
        -H "Content-Type: application/json" \
        -d "{\"admin_username\": \"$input_user\", \"admin_token\": \"$input_token\"}")
        
    if echo "$response" | grep -q "success\|reset"; then
        log_success "Database reset successful."
        echo "$response" | python3 -m json.tool 2>/dev/null || echo "$response"
    else
        log_error "Database reset failed. Invalid credentials or backend offline."
        echo "Response: $response"
    fi
}

db_query() {
    check_env
    local db_name=${MONGODB_NAME:-betting_game}
    
    echo -e "${YELLOW}Enter your MongoDB query (e.g., db.players.find().limit(5)):${NC}"
    read -p "> " user_query
    
    if [ -z "$user_query" ]; then
        log_error "Query cannot be empty."
        return 1
    fi

    log_info "Executing query on database: $db_name"
    
    if command -v docker >/dev/null 2>&1 && docker ps | grep -q "mongodb"; then
        docker exec -it mongodb mongosh --quiet "$db_name" --eval "$user_query"
    else
        log_error "MongoDB container is not running. Start it with './run.sh docker up'"
    fi
}

update_env_var() {
    local key=$1
    local value=$2
    if grep -q "^$key=" "$ENV_FILE"; then
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s/^$key=.*/$key=$value/" "$ENV_FILE"
        else
            sed -i "s/^$key=.*/$key=$value/" "$ENV_FILE"
        fi
    else
        echo "$key=$value" >> "$ENV_FILE"
    fi
}

db_config() {
    log_info "Updating Admin Credentials..."
    read -p "Enter new Admin Username [default: admin]: " new_user
    new_user=${new_user:-admin}
    read -p "Enter new Admin Token: " new_token
    
    if [ -z "$new_token" ]; then
        log_error "Token cannot be empty."
        return
    fi
    
    update_env_var "ADMIN_RESET_USERNAME" "$new_user"
    update_env_var "ADMIN_RESET_TOKEN" "$new_token"
    
    log_success "Credentials updated in $ENV_FILE."
}

show_logs() {
    case $2 in
        --frontend) 
            log_info "Frontend logs (manual) aren't stored in a file by default."
            log_info "Please check the terminal where you ran './run.sh start --frontend'"
            ;;
        --backend)
            log_info "Backend logs (manual) aren't stored in a file by default."
            log_info "Please check the terminal where you ran './run.sh start --backend'"
            ;;
        *)
            log_info "Tailing all docker logs..."
            docker-compose logs -f
            ;;
    esac
}

# --- INTERACTIVE MENU ---

interactive_menu() {
    while true; do
        clear
        echo -e "${CYAN}==========================================${NC}"
        echo -e "${CYAN}    BETTING GAME - MANAGEMENT SHELL       ${NC}"
        echo -e "${CYAN}==========================================${NC}"
        echo -e "1) ${GREEN}Start Services${NC} (Dev Mode)"
        echo -e "2) ${GREEN}Build Services${NC}"
        echo -e "3) ${GREEN}Docker Commands${NC} (Up/Down/Build/Logs)"
        echo -e "4) ${GREEN}Database Tools${NC} (Reset/Config/Query)"
        echo -e "5) ${GREEN}Environment Management${NC} (.env Setup/Verify/Update)"
        echo -e "6) ${GREEN}System Check${NC} (Dependencies/Running Services)"
        echo -e "0) ${RED}Exit${NC}"
        echo -e "${CYAN}==========================================${NC}"
        read -p "Select an option [0-6]: " choice

        case $choice in
            1)
                echo -e "\n1) Start All\n2) Start Frontend\n3) Start Backend\n0) Back"
                read -p "Selection: " subchoice
                case $subchoice in
                    1) check_env && start_all ;;
                    2) check_env && start_frontend ;;
                    3) check_env && start_backend ;;
                esac
                ;;
            2)
                echo -e "\n1) Build All\n2) Build Frontend\n3) Build Backend\n0) Back"
                read -p "Selection: " subchoice
                case $subchoice in
                    1) build_backend; build_frontend ;;
                    2) build_frontend ;;
                    3) build_backend ;;
                esac
                read -p "Press Enter to continue..."
                ;;
            3)
                echo -e "\n1) Docker Up\n2) Docker Down\n3) Docker Build\n4) Docker Logs\n0) Back"
                read -p "Selection: " subchoice
                case $subchoice in
                    1) docker_cmd "up" ;;
                    2) docker_cmd "down" ;;
                    3) docker_cmd "build" ;;
                    4) docker_cmd "logs" ;;
                esac
                read -p "Press Enter to continue..."
                ;;
            4)
                echo -e "\n1) Reset Database (API)\n2) Configure Admin Credentials\n3) Run MongoDB Query\n0) Back"
                read -p "Selection: " subchoice
                case $subchoice in
                    1) db_reset ;;
                    2) db_config ;;
                    3) db_query ;;
                esac
                read -p "Press Enter to continue..."
                ;;
            5)
                echo -e "\n1) Verify .env\n2) Run Step-by-Step Wizard\n3) Reset .env from Example\n0) Back"
                read -p "Selection: " subchoice
                case $subchoice in
                    1) 
                        if [ -f "$ENV_FILE" ]; then
                            log_success ".env file exists."
                            log_info "Content preview:"
                            head -n 5 "$ENV_FILE"
                            echo "..."
                        else
                            log_warn ".env file is missing."
                            check_env
                        fi
                        ;;
                    2) env_wizard ;;
                    3) 
                        read -p "Are you sure? This will overwrite your .env [y/N]: " confirm
                        if [[ $confirm == [yY] ]]; then
                            cp .env.example "$ENV_FILE"
                            log_success ".env reset to default."
                        fi
                        ;;
                esac
                read -p "Press Enter to continue..."
                ;;
            6)
                run_full_check
                read -p "Press Enter to continue..."
                ;;
            0)
                log_info "Goodbye!"
                exit 0
                ;;
            *)
                log_error "Invalid option"
                sleep 1
                ;;
        esac
    done
}

start_all() {
    log_info "Starting both services in parallel..."
    log_warn "This will run in the foreground. Use Ctrl+C to stop."
    trap "kill 0" EXIT
    (start_backend) & (start_frontend)
    wait
}

# --- MAIN ---

if [ $# -eq 0 ]; then
    interactive_menu
else
    case $1 in
        help)
            show_help
            ;;
        check)
            run_full_check
            ;;
        start)
            check_env
            case $2 in
                --frontend) start_frontend ;;
                --backend) start_backend ;;
                --all|*) start_all ;;
            esac
            ;;
        build)
            case $2 in
                --frontend) build_frontend ;;
                --backend) build_backend ;;
                --all|*) build_backend; build_frontend ;;
            esac
            ;;
        docker)
            docker_cmd "$2"
            ;;
        db)
            case $2 in
                reset) db_reset ;;
                config) db_config ;;
                *) log_error "Invalid db command: $2. Use 'reset' or 'config'." ;;
            esac
            ;;
        logs)
            show_logs "$@"
            ;;
        *)
            log_error "Unknown command: $1"
            show_help
            exit 1
            ;;
    esac
fi
